export type StudioProject = {
  slug: string;
  name: string;
  initials: string;
  platform: string;
  branch: string;
  latest: string;
  commit: string;
  stable: string;
  live: string;
  state: string;
  updated: string;
  publicSummary: string;
  skills: string[];
  featured?: boolean;
};

export const studioProjects: StudioProject[] = [
  {
    slug: "dtp-master",
    name: "DTP Master",
    initials: "DT",
    platform: "Windows · macOS",
    branch: "import/local-v1.5",
    latest: "v1.5 development source validated",
    commit: "d9cd49e",
    stable: "v1.4",
    live: "v1.4 installer",
    state: "In development",
    updated: "Jul 2026",
    publicSummary: "A production workflow tool that turns complex multilingual DTP tasks into a repeatable desktop process.",
    skills: ["Python", "Desktop", "DTP automation"],
    featured: true,
  },
  {
    slug: "mahmoud-jp",
    name: "mahmoud.jp",
    initials: "MJ",
    platform: "Web · Vercel",
    branch: "master",
    latest: "Mahmoud Studio launched with Google-only owner access",
    commit: "5827f19",
    stable: "Studio launch",
    live: "mahmoud.jp",
    state: "Live",
    updated: "Aug 2026",
    publicSummary: "A multilingual portfolio and private Studio presenting DTP, language, product, and IT work through one personal brand.",
    skills: ["Next.js", "React", "Vercel"],
    featured: true,
  },
  {
    slug: "mylife",
    name: "MyLife",
    initials: "ML",
    platform: "Android · iOS · Web",
    branch: "main",
    latest: "TypeScript typecheck passed",
    commit: "515c80e",
    stable: "Not tagged",
    live: "Not released",
    state: "In development",
    updated: "Jul 2026",
    publicSummary: "A cross-platform personal system for organizing the information and routines that shape everyday life.",
    skills: ["TypeScript", "Mobile", "Product design"],
    featured: true,
  },
  {
    slug: "jlpt-master",
    name: "JLPT Master",
    initials: "JL",
    platform: "Web",
    branch: "main",
    latest: "28 tests and production build passed",
    commit: "3217ff2",
    stable: "Build validated",
    live: "Not deployed",
    state: "Ready for review",
    updated: "Jul 2026",
    publicSummary: "A focused Japanese study experience built around structured practice and measurable progress.",
    skills: ["React", "Testing", "Japanese learning"],
  },
  {
    slug: "cloudops-associate",
    name: "CloudOps Associate",
    initials: "CL",
    platform: "Windows · macOS",
    branch: "main",
    latest: "Frontend production build passed",
    commit: "4c26bb3",
    stable: "Build validated",
    live: "Not released",
    state: "In development",
    updated: "Jul 2026",
    publicSummary: "A desktop learning companion for cloud operations concepts, review, and exam preparation.",
    skills: ["Cloud", "Desktop", "Learning systems"],
  },
  {
    slug: "koryuu",
    name: "Koryuu",
    initials: "KO",
    platform: "Web · Cloudflare",
    branch: "main",
    latest: "Source and production build validated",
    commit: "a28cc5e",
    stable: "Source validated",
    live: "Not deployed",
    state: "Ready for review",
    updated: "Jul 2026",
    publicSummary: "A language-focused web product shaped by multilingual communication and practical Japanese use.",
    skills: ["Web", "Cloudflare", "Localization"],
  },
  {
    slug: "mind-map",
    name: "Mind Map",
    initials: "MM",
    platform: "Interactive web",
    branch: "main",
    latest: "Private cloud sync migration",
    commit: "bf444d7",
    stable: "v11 source",
    live: "Mahmoud Studio",
    state: "Active",
    updated: "Aug 2026",
    publicSummary: "A visual thinking canvas designed to capture ideas before they disappear and connect them over time.",
    skills: ["JavaScript", "UX", "Knowledge tools"],
  },
  {
    slug: "supernotch",
    name: "SuperNotch",
    initials: "SN",
    platform: "macOS",
    branch: "main",
    latest: "Source organized for Mac testing",
    commit: "0de21dd",
    stable: "Not tagged",
    live: "Not released",
    state: "Needs Mac testing",
    updated: "Jul 2026",
    publicSummary: "A focused macOS utility experiment built around improving a small but repeated interaction.",
    skills: ["macOS", "Utility", "Interaction design"],
  },
  {
    slug: "switcher",
    name: "Switcher",
    initials: "SW",
    platform: "macOS",
    branch: "main",
    latest: "Source organized for Mac testing",
    commit: "93e8e69",
    stable: "Not tagged",
    live: "Not released",
    state: "Needs Mac testing",
    updated: "Jul 2026",
    publicSummary: "A compact macOS productivity experiment for switching context with less friction.",
    skills: ["macOS", "Productivity", "Prototype"],
  },
  {
    slug: "snake",
    name: "Snake",
    initials: "SK",
    platform: "Web",
    branch: "main",
    latest: "JavaScript syntax checks passed",
    commit: "ec31c40",
    stable: "Source validated",
    live: "Not deployed",
    state: "Complete",
    updated: "Jul 2026",
    publicSummary: "A compact browser game used to explore interaction, pacing, and polished small-screen behavior.",
    skills: ["JavaScript", "Game UI", "Web"],
  },
];

export const featuredStudioProjects = studioProjects.filter((project) => project.featured);
